title: PT2IB JARIO
logo: /assets/img/logo.png
description: Em modo simplex VHF 146.580Mhz. 

callsig: PT2IB
cb: PX9I6147
grid: GH64bf

show_downloads: false
project_page: false
user_page: false
project_page: false

google_analytics:
theme: jekyll-theme-minimal
